spring:
  datasource:
    url: jdbc:mysql://192.168.110.114:46821/Test?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: fwadmin
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080

